siteTitle: "Linkora Sync-Server | Documentation"
siteTopBarTitle: "Linkora Sync-Server"

sideNavBarItems:
  - label: "Introduction"
    filePath: "index.md"

  - label: "Getting Started"
    isHeading: true
  - label: "Prerequisites"
    filePath: "getting-started/prerequisites.md"
  - label: "HTTPS Setup"
    filePath: "getting-started/https.md"

  - label: "Configuration"
    isHeading: true
  - label: "Config File & Env Vars"
    filePath: "configuration/config-file-env-vars.md"
  - label: "Database Setup"
    filePath: "configuration/database.md"

  - label: "Deployment"
    isHeading: true
  - label: "Local JAR"
    filePath: "deployment/local-jar.md"
  - label: "Docker"
    filePath: "deployment/docker.md"
  - label: "Cloud Hosting"
    filePath: "deployment/cloud.md"

  - label: "Advanced"
    isHeading: true
  - label: "Systemd Service"
    filePath: "advanced/systemd.md"
  - label: "Nginx WebSocket Proxy"
    filePath: "advanced/nginx-websocket-proxy.md"
  - label: "Firewall Setup"
    filePath: "advanced/firewall.md"
  - label: "Security Notes"
    filePath: "advanced/security.md"

  - isDivider: true

  - label: "Troubleshooting"
    filePath: "troubleshooting.md"

  - label: "How It Works"
    filePath: "how-it-works.md"

  - label: "Browser Extension"
    filePath: "browser-extension.md"
